#plt.show()# -*- coding: utf-8 -*-

import icons

from PyQt5 import QtCore, QtGui, QtWidgets

from matplotlib.backends.backend_qt5agg import (FigureCanvasQTAgg as FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.backends.qt_compat import QtCore, QtWidgets
from matplotlib.figure import Figure
from matplotlib import dates as mdates
from matplotlib import style
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import Divider, Size
from mpl_toolkits.axes_grid1.mpl_axes import Axes

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lay_datetime = QtWidgets.QGridLayout()
        self.lay_datetime.setObjectName("lay_datetime")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lay_datetime.addItem(spacerItem, 0, 1, 1, 1)
        self.lbl_time = QtWidgets.QLabel(self.centralwidget)
        self.lbl_time.setObjectName("lbl_time")
        self.lay_datetime.addWidget(self.lbl_time, 0, 2, 1, 1)
        self.lbl_lturesource_txt = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lturesource_txt.setFont(font)
        self.lbl_lturesource_txt.setObjectName("lbl_lturesource_txt")
        self.lay_datetime.addWidget(self.lbl_lturesource_txt, 0, 0, 1, 1)
        self.lbl_spacer = QtWidgets.QLabel(self.centralwidget)
        self.lbl_spacer.setText("")
        self.lbl_spacer.setObjectName("lbl_spacer")
        self.lay_datetime.addWidget(self.lbl_spacer, 0, 3, 1, 1)
        self.lbl_date = QtWidgets.QLabel(self.centralwidget)
        self.lbl_date.setObjectName("lbl_date")
        self.lay_datetime.addWidget(self.lbl_date, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.lay_datetime, 2, 0, 1, 1)
        self.tab_mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_mainTab.setObjectName("tab_mainTab")
        self.tab_main_1 = QtWidgets.QWidget()
        self.tab_main_1.setObjectName("tab_main_1")
        self.lbl_tmp_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_txt.setGeometry(QtCore.QRect(10, 0, 701, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_txt.setFont(font)
        self.lbl_tmp_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_txt.setObjectName("lbl_tmp_txt")
        self.hor_line_1 = QtWidgets.QFrame(self.tab_main_1)
        self.hor_line_1.setGeometry(QtCore.QRect(10, 10, 711, 20))
        self.hor_line_1.setLineWidth(2)
        self.hor_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_1.setObjectName("hor_line_1")
        self.lbl_tmp_ch_1 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_1.setGeometry(QtCore.QRect(150, 30, 91, 20))
        self.lbl_tmp_ch_1.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_1.setObjectName("lbl_tmp_ch_1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 661, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_tmp_ch_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_tmp_ch_1.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_1.setObjectName("lay_tmp_ch_1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 661, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.lay_tmp_ch_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.lay_tmp_ch_2.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_2.setObjectName("lay_tmp_ch_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 230, 661, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.lay_tmp_ch_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.lay_tmp_ch_3.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_3.setObjectName("lay_tmp_ch_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 320, 661, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.lay_tmp_ch_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.lay_tmp_ch_4.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_4.setObjectName("lay_tmp_ch_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 410, 661, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.lay_tmp_ch_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.lay_tmp_ch_5.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_5.setObjectName("lay_tmp_ch_5")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 500, 661, 71))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.lay_tmp_ch_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.lay_tmp_ch_6.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_6.setObjectName("lay_tmp_ch_6")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 590, 661, 71))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.lay_tmp_ch_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.lay_tmp_ch_7.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_7.setObjectName("lay_tmp_ch_7")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab_main_1)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 680, 661, 91))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.lay_tmp_ch_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.lay_tmp_ch_8.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_ch_8.setObjectName("lay_tmp_ch_8")
        self.lbl_tmp_ch_2 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_2.setGeometry(QtCore.QRect(150, 120, 91, 20))
        self.lbl_tmp_ch_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_2.setObjectName("lbl_tmp_ch_2")
        self.lbl_tmp_ch_3 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_3.setGeometry(QtCore.QRect(150, 210, 91, 20))
        self.lbl_tmp_ch_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_3.setObjectName("lbl_tmp_ch_3")
        self.lbl_tmp_ch_4 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_4.setGeometry(QtCore.QRect(150, 300, 91, 20))
        self.lbl_tmp_ch_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_4.setObjectName("lbl_tmp_ch_4")
        self.lbl_tmp_ch_5 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_5.setGeometry(QtCore.QRect(150, 390, 91, 20))
        self.lbl_tmp_ch_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_5.setObjectName("lbl_tmp_ch_5")
        self.lbl_tmp_ch_6 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_6.setGeometry(QtCore.QRect(150, 480, 91, 20))
        self.lbl_tmp_ch_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_6.setObjectName("lbl_tmp_ch_6")
        self.lbl_tmp_ch_7 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_7.setGeometry(QtCore.QRect(150, 570, 91, 20))
        self.lbl_tmp_ch_7.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_7.setObjectName("lbl_tmp_ch_7")
        self.lbl_tmp_ch_8 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_8.setGeometry(QtCore.QRect(150, 660, 91, 20))
        self.lbl_tmp_ch_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_8.setObjectName("lbl_tmp_ch_8")
        self.lbl_act_tmp_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_txt.setGeometry(QtCore.QRect(670, 30, 51, 16))
        self.lbl_act_tmp_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_txt.setObjectName("lbl_act_tmp_txt")
        self.lbl_act_tmp_ch_1 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_1.setGeometry(QtCore.QRect(670, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_1.setFont(font)
        self.lbl_act_tmp_ch_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_1.setObjectName("lbl_act_tmp_ch_1")
        self.lbl_act_tmp_ch_2 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_2.setGeometry(QtCore.QRect(670, 160, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_2.setFont(font)
        self.lbl_act_tmp_ch_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_2.setObjectName("lbl_act_tmp_ch_2")
        self.lbl_act_tmp_ch_3 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_3.setGeometry(QtCore.QRect(670, 250, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_3.setFont(font)
        self.lbl_act_tmp_ch_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_3.setObjectName("lbl_act_tmp_ch_3")
        self.lbl_act_tmp_ch_4 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_4.setGeometry(QtCore.QRect(670, 340, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_4.setFont(font)
        self.lbl_act_tmp_ch_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_4.setObjectName("lbl_act_tmp_ch_4")
        self.lbl_act_tmp_ch_5 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_5.setGeometry(QtCore.QRect(670, 430, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_5.setFont(font)
        self.lbl_act_tmp_ch_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_5.setObjectName("lbl_act_tmp_ch_5")
        self.lbl_act_tmp_ch_6 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_6.setGeometry(QtCore.QRect(670, 520, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_6.setFont(font)
        self.lbl_act_tmp_ch_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_6.setObjectName("lbl_act_tmp_ch_6")
        self.lbl_act_tmp_ch_7 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_7.setGeometry(QtCore.QRect(670, 610, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_7.setFont(font)
        self.lbl_act_tmp_ch_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_7.setObjectName("lbl_act_tmp_ch_7")
        self.lbl_act_tmp_ch_8 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_tmp_ch_8.setGeometry(QtCore.QRect(670, 700, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_act_tmp_ch_8.setFont(font)
        self.lbl_act_tmp_ch_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_tmp_ch_8.setObjectName("lbl_act_tmp_ch_8")
        self.vert_line_1 = QtWidgets.QFrame(self.tab_main_1)
        self.vert_line_1.setGeometry(QtCore.QRect(720, 10, 20, 751))
        self.vert_line_1.setLineWidth(2)
        self.vert_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vert_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vert_line_1.setObjectName("vert_line_1")
        self.lbl_set = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_set.setGeometry(QtCore.QRect(720, 0, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_set.setFont(font)
        self.lbl_set.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_set.setObjectName("lbl_set")
        self.lbl_choose_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_choose_txt.setGeometry(QtCore.QRect(740, 50, 101, 21))
        self.lbl_choose_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_choose_txt.setObjectName("lbl_choose_txt")
        self.ch_com_port = QtWidgets.QComboBox(self.tab_main_1)
        self.ch_com_port.setGeometry(QtCore.QRect(840, 50, 91, 21))
        self.ch_com_port.setObjectName("ch_com_port")
        self.lbl_connect_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_connect_txt.setGeometry(QtCore.QRect(740, 20, 391, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_connect_txt.setFont(font)
        self.lbl_connect_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.lbl_connect_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_connect_txt.setObjectName("lbl_connect_txt")
        self.btn_connect = QtWidgets.QPushButton(self.tab_main_1)
        self.btn_connect.setEnabled(False)
        self.btn_connect.setGeometry(QtCore.QRect(960, 50, 81, 23))
        self.btn_connect.setObjectName("btn_connect")
        self.btn_disconnect = QtWidgets.QPushButton(self.tab_main_1)
        self.btn_disconnect.setEnabled(False)
        self.btn_disconnect.setGeometry(QtCore.QRect(1050, 50, 81, 23))
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.lbl_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_track_txt.setGeometry(QtCore.QRect(740, 110, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_track_txt.setFont(font)
        self.lbl_track_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.lbl_track_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_track_txt.setObjectName("lbl_track_txt")
        self.lbl_tmp_ch_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_txt.setGeometry(QtCore.QRect(740, 160, 61, 16))
        self.lbl_tmp_ch_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_txt.setObjectName("lbl_tmp_ch_txt")
        self.lbl_act_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_track_txt.setGeometry(QtCore.QRect(830, 160, 51, 16))
        self.lbl_act_track_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_track_txt.setObjectName("lbl_act_track_txt")
        self.lbl_tmp_ch_1_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_1_track_txt.setGeometry(QtCore.QRect(750, 190, 61, 16))
        self.lbl_tmp_ch_1_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_1_track_txt.setObjectName("lbl_tmp_ch_1_track_txt")
        self.lbl_tmp_ch_2_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_2_track_txt.setGeometry(QtCore.QRect(750, 210, 61, 16))
        self.lbl_tmp_ch_2_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_2_track_txt.setObjectName("lbl_tmp_ch_2_track_txt")
        self.lbl_tmp_ch_3_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_3_track_txt.setGeometry(QtCore.QRect(750, 230, 61, 16))
        self.lbl_tmp_ch_3_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_3_track_txt.setObjectName("lbl_tmp_ch_3_track_txt")
        self.lbl_tmp_ch_4_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_4_track_txt.setGeometry(QtCore.QRect(750, 250, 61, 16))
        self.lbl_tmp_ch_4_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_4_track_txt.setObjectName("lbl_tmp_ch_4_track_txt")
        self.lbl_tmp_ch_5_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_5_track_txt.setGeometry(QtCore.QRect(750, 270, 61, 16))
        self.lbl_tmp_ch_5_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_5_track_txt.setObjectName("lbl_tmp_ch_5_track_txt")
        self.lbl_tmp_ch_6_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_6_track_txt.setGeometry(QtCore.QRect(750, 290, 61, 16))
        self.lbl_tmp_ch_6_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_6_track_txt.setObjectName("lbl_tmp_ch_6_track_txt")
        self.lbl_tmp_ch_7_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_7_track_txt.setGeometry(QtCore.QRect(750, 310, 61, 16))
        self.lbl_tmp_ch_7_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_7_track_txt.setObjectName("lbl_tmp_ch_7_track_txt")
        self.lbl_tmp_ch_8_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_8_track_txt.setGeometry(QtCore.QRect(750, 330, 61, 16))
        self.lbl_tmp_ch_8_track_txt.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_tmp_ch_8_track_txt.setObjectName("lbl_tmp_ch_8_track_txt")
        self.ed_tmp_min_ch_1 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_1.setEnabled(False)
        self.ed_tmp_min_ch_1.setGeometry(QtCore.QRect(920, 190, 61, 16))
        self.ed_tmp_min_ch_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_1.setObjectName("ed_tmp_min_ch_1")
        self.lbl_min_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_min_track_txt.setGeometry(QtCore.QRect(920, 160, 61, 16))
        self.lbl_min_track_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_min_track_txt.setObjectName("lbl_min_track_txt")
        self.lbl_max_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_max_track_txt.setGeometry(QtCore.QRect(990, 160, 61, 16))
        self.lbl_max_track_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_max_track_txt.setObjectName("lbl_max_track_txt")
        self.ch_tmp_ch_1 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_1.setEnabled(False)
        self.ch_tmp_ch_1.setGeometry(QtCore.QRect(1080, 190, 16, 17))
        self.ch_tmp_ch_1.setText("")
        self.ch_tmp_ch_1.setObjectName("ch_tmp_ch_1")
        self.lbl_check_track_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_check_track_txt.setGeometry(QtCore.QRect(1060, 160, 51, 16))
        self.lbl_check_track_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_check_track_txt.setObjectName("lbl_check_track_txt")
        self.lbl_tmp_ch_1_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_1_track.setGeometry(QtCore.QRect(830, 190, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_1_track.setFont(font)
        self.lbl_tmp_ch_1_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_1_track.setObjectName("lbl_tmp_ch_1_track")
        self.lbl_tmp_ch_2_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_2_track.setGeometry(QtCore.QRect(830, 210, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_2_track.setFont(font)
        self.lbl_tmp_ch_2_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_2_track.setObjectName("lbl_tmp_ch_2_track")
        self.lbl_tmp_ch_3_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_3_track.setGeometry(QtCore.QRect(830, 230, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_3_track.setFont(font)
        self.lbl_tmp_ch_3_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_3_track.setObjectName("lbl_tmp_ch_3_track")
        self.lbl_tmp_ch_4_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_4_track.setGeometry(QtCore.QRect(830, 250, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_4_track.setFont(font)
        self.lbl_tmp_ch_4_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_4_track.setObjectName("lbl_tmp_ch_4_track")
        self.lbl_tmp_ch_5_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_5_track.setGeometry(QtCore.QRect(830, 270, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_5_track.setFont(font)
        self.lbl_tmp_ch_5_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_5_track.setObjectName("lbl_tmp_ch_5_track")
        self.lbl_tmp_ch_6_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_6_track.setGeometry(QtCore.QRect(830, 290, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_6_track.setFont(font)
        self.lbl_tmp_ch_6_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_6_track.setObjectName("lbl_tmp_ch_6_track")
        self.lbl_tmp_ch_7_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_7_track.setGeometry(QtCore.QRect(830, 310, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_7_track.setFont(font)
        self.lbl_tmp_ch_7_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_7_track.setObjectName("lbl_tmp_ch_7_track")
        self.lbl_tmp_ch_8_track = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_8_track.setGeometry(QtCore.QRect(830, 330, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_ch_8_track.setFont(font)
        self.lbl_tmp_ch_8_track.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_8_track.setObjectName("lbl_tmp_ch_8_track")
        self.ed_tmp_min_ch_2 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_2.setEnabled(False)
        self.ed_tmp_min_ch_2.setGeometry(QtCore.QRect(920, 210, 61, 16))
        self.ed_tmp_min_ch_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_2.setObjectName("ed_tmp_min_ch_2")
        self.ed_tmp_min_ch_3 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_3.setEnabled(False)
        self.ed_tmp_min_ch_3.setGeometry(QtCore.QRect(920, 230, 61, 16))
        self.ed_tmp_min_ch_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_3.setObjectName("ed_tmp_min_ch_3")
        self.ed_tmp_min_ch_4 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_4.setEnabled(False)
        self.ed_tmp_min_ch_4.setGeometry(QtCore.QRect(920, 250, 61, 16))
        self.ed_tmp_min_ch_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_4.setObjectName("ed_tmp_min_ch_4")
        self.ed_tmp_min_ch_5 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_5.setEnabled(False)
        self.ed_tmp_min_ch_5.setGeometry(QtCore.QRect(920, 270, 61, 16))
        self.ed_tmp_min_ch_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_5.setObjectName("ed_tmp_min_ch_5")
        self.ed_tmp_min_ch_6 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_6.setEnabled(False)
        self.ed_tmp_min_ch_6.setGeometry(QtCore.QRect(920, 290, 61, 16))
        self.ed_tmp_min_ch_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_6.setObjectName("ed_tmp_min_ch_6")
        self.ed_tmp_min_ch_7 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_7.setEnabled(False)
        self.ed_tmp_min_ch_7.setGeometry(QtCore.QRect(920, 310, 61, 16))
        self.ed_tmp_min_ch_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_7.setObjectName("ed_tmp_min_ch_7")
        self.ed_tmp_min_ch_8 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_min_ch_8.setEnabled(False)
        self.ed_tmp_min_ch_8.setGeometry(QtCore.QRect(920, 330, 61, 16))
        self.ed_tmp_min_ch_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_min_ch_8.setObjectName("ed_tmp_min_ch_8")
        self.ed_tmp_max_ch_1 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_1.setEnabled(False)
        self.ed_tmp_max_ch_1.setGeometry(QtCore.QRect(990, 190, 61, 16))
        self.ed_tmp_max_ch_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_1.setObjectName("ed_tmp_max_ch_1")
        self.ed_tmp_max_ch_2 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_2.setEnabled(False)
        self.ed_tmp_max_ch_2.setGeometry(QtCore.QRect(990, 210, 61, 16))
        self.ed_tmp_max_ch_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_2.setObjectName("ed_tmp_max_ch_2")
        self.ed_tmp_max_ch_3 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_3.setEnabled(False)
        self.ed_tmp_max_ch_3.setGeometry(QtCore.QRect(990, 230, 61, 16))
        self.ed_tmp_max_ch_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_3.setObjectName("ed_tmp_max_ch_3")
        self.ed_tmp_max_ch_4 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_4.setEnabled(False)
        self.ed_tmp_max_ch_4.setGeometry(QtCore.QRect(990, 250, 61, 16))
        self.ed_tmp_max_ch_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_4.setObjectName("ed_tmp_max_ch_4")
        self.ed_tmp_max_ch_5 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_5.setEnabled(False)
        self.ed_tmp_max_ch_5.setGeometry(QtCore.QRect(990, 270, 61, 16))
        self.ed_tmp_max_ch_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_5.setObjectName("ed_tmp_max_ch_5")
        self.ed_tmp_max_ch_6 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_6.setEnabled(False)
        self.ed_tmp_max_ch_6.setGeometry(QtCore.QRect(990, 290, 61, 16))
        self.ed_tmp_max_ch_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_6.setObjectName("ed_tmp_max_ch_6")
        self.ed_tmp_max_ch_7 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_7.setEnabled(False)
        self.ed_tmp_max_ch_7.setGeometry(QtCore.QRect(990, 310, 61, 16))
        self.ed_tmp_max_ch_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_7.setObjectName("ed_tmp_max_ch_7")
        self.ed_tmp_max_ch_8 = QtWidgets.QLineEdit(self.tab_main_1)
        self.ed_tmp_max_ch_8.setEnabled(False)
        self.ed_tmp_max_ch_8.setGeometry(QtCore.QRect(990, 330, 61, 16))
        self.ed_tmp_max_ch_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ed_tmp_max_ch_8.setObjectName("ed_tmp_max_ch_8")
        self.ch_tmp_ch_2 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_2.setEnabled(False)
        self.ch_tmp_ch_2.setGeometry(QtCore.QRect(1080, 210, 16, 17))
        self.ch_tmp_ch_2.setText("")
        self.ch_tmp_ch_2.setObjectName("ch_tmp_ch_2")
        self.ch_tmp_ch_3 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_3.setEnabled(False)
        self.ch_tmp_ch_3.setGeometry(QtCore.QRect(1080, 230, 16, 17))
        self.ch_tmp_ch_3.setText("")
        self.ch_tmp_ch_3.setObjectName("ch_tmp_ch_3")
        self.ch_tmp_ch_4 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_4.setEnabled(False)
        self.ch_tmp_ch_4.setGeometry(QtCore.QRect(1080, 250, 16, 17))
        self.ch_tmp_ch_4.setText("")
        self.ch_tmp_ch_4.setObjectName("ch_tmp_ch_4")
        self.ch_tmp_ch_5 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_5.setEnabled(False)
        self.ch_tmp_ch_5.setGeometry(QtCore.QRect(1080, 270, 16, 17))
        self.ch_tmp_ch_5.setText("")
        self.ch_tmp_ch_5.setObjectName("ch_tmp_ch_5")
        self.ch_tmp_ch_6 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_6.setEnabled(False)
        self.ch_tmp_ch_6.setGeometry(QtCore.QRect(1080, 290, 16, 17))
        self.ch_tmp_ch_6.setText("")
        self.ch_tmp_ch_6.setObjectName("ch_tmp_ch_6")
        self.ch_tmp_ch_7 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_7.setEnabled(False)
        self.ch_tmp_ch_7.setGeometry(QtCore.QRect(1080, 310, 16, 17))
        self.ch_tmp_ch_7.setText("")
        self.ch_tmp_ch_7.setObjectName("ch_tmp_ch_7")
        self.ch_tmp_ch_8 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_ch_8.setEnabled(False)
        self.ch_tmp_ch_8.setGeometry(QtCore.QRect(1080, 330, 16, 17))
        self.ch_tmp_ch_8.setText("")
        self.ch_tmp_ch_8.setObjectName("ch_tmp_ch_8")
        self.lbl_act_track_txt_2 = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_act_track_txt_2.setGeometry(QtCore.QRect(920, 140, 131, 16))
        self.lbl_act_track_txt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_act_track_txt_2.setObjectName("lbl_act_track_txt_2")
        self.lbl_save_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_save_txt.setGeometry(QtCore.QRect(740, 690, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_save_txt.setFont(font)
        self.lbl_save_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.lbl_save_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_save_txt.setObjectName("lbl_save_txt")
        self.ch_save_to_file = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_save_to_file.setEnabled(False)
        self.ch_save_to_file.setGeometry(QtCore.QRect(1050, 720, 81, 17))
        self.ch_save_to_file.setObjectName("ch_save_to_file")
        self.bth_create_logfile = QtWidgets.QPushButton(self.tab_main_1)
        self.bth_create_logfile.setGeometry(QtCore.QRect(1050, 740, 41, 31))
        self.bth_create_logfile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bth_create_logfile.setIcon(icon)
        self.bth_create_logfile.setIconSize(QtCore.QSize(25, 25))
        self.bth_create_logfile.setObjectName("bth_create_logfile")
        self.lbl_ed_logpath = QtWidgets.QTextEdit(self.tab_main_1)
        self.lbl_ed_logpath.setEnabled(False)
        self.lbl_ed_logpath.setGeometry(QtCore.QRect(740, 720, 301, 51))
        self.lbl_ed_logpath.setObjectName("lbl_ed_logpath")
        self.lbl_disp_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_disp_txt.setGeometry(QtCore.QRect(740, 450, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_disp_txt.setFont(font)
        self.lbl_disp_txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.lbl_disp_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_disp_txt.setObjectName("lbl_disp_txt")
        self.gb_tmp_pts = QtWidgets.QGroupBox(self.tab_main_1)
        self.gb_tmp_pts.setEnabled(False)
        self.gb_tmp_pts.setGeometry(QtCore.QRect(740, 540, 291, 91))
        self.gb_tmp_pts.setObjectName("gb_tmp_pts")
        self.btn_tmp_pts_1 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_1.setGeometry(QtCore.QRect(10, 20, 61, 17))
        self.btn_tmp_pts_1.setObjectName("btn_tmp_pts_1")
        self.btn_tmp_pts_2 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_2.setGeometry(QtCore.QRect(10, 40, 61, 17))
        self.btn_tmp_pts_2.setObjectName("btn_tmp_pts_2")
        self.btn_tmp_pts_3 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_3.setGeometry(QtCore.QRect(10, 60, 61, 17))
        self.btn_tmp_pts_3.setObjectName("btn_tmp_pts_3")
        self.btn_tmp_pts_4 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_4.setGeometry(QtCore.QRect(80, 20, 61, 17))
        self.btn_tmp_pts_4.setObjectName("btn_tmp_pts_4")
        self.btn_tmp_pts_5 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_5.setGeometry(QtCore.QRect(80, 40, 61, 17))
        self.btn_tmp_pts_5.setObjectName("btn_tmp_pts_5")
        self.btn_tmp_pts_6 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_6.setGeometry(QtCore.QRect(80, 60, 61, 17))
        self.btn_tmp_pts_6.setObjectName("btn_tmp_pts_6")
        self.btn_tmp_pts_7 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_7.setGeometry(QtCore.QRect(150, 20, 61, 17))
        self.btn_tmp_pts_7.setObjectName("btn_tmp_pts_7")
        self.btn_tmp_pts_8 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_8.setGeometry(QtCore.QRect(150, 40, 61, 17))
        self.btn_tmp_pts_8.setObjectName("btn_tmp_pts_8")
        self.btn_tmp_pts_9 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_9.setGeometry(QtCore.QRect(150, 60, 61, 17))
        self.btn_tmp_pts_9.setObjectName("btn_tmp_pts_9")
        self.btn_tmp_pts_10 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_10.setGeometry(QtCore.QRect(220, 20, 61, 17))
        self.btn_tmp_pts_10.setObjectName("btn_tmp_pts_10")
        self.btn_tmp_pts_11 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_11.setGeometry(QtCore.QRect(220, 40, 61, 17))
        self.btn_tmp_pts_11.setObjectName("btn_tmp_pts_11")
        self.btn_tmp_pts_12 = QtWidgets.QRadioButton(self.gb_tmp_pts)
        self.btn_tmp_pts_12.setGeometry(QtCore.QRect(220, 60, 61, 17))
        self.btn_tmp_pts_12.setChecked(True)
        self.btn_tmp_pts_12.setObjectName("btn_tmp_pts_12")
        self.lbl_totalpts_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_totalpts_txt.setEnabled(False)
        self.lbl_totalpts_txt.setGeometry(QtCore.QRect(1040, 560, 91, 20))
        self.lbl_totalpts_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_totalpts_txt.setObjectName("lbl_totalpts_txt")
        self.lbl_tmp_totalpts = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_totalpts.setEnabled(False)
        self.lbl_tmp_totalpts.setGeometry(QtCore.QRect(1040, 580, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tmp_totalpts.setFont(font)
        self.lbl_tmp_totalpts.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_totalpts.setObjectName("lbl_tmp_totalpts")
        self.hor_line_2 = QtWidgets.QFrame(self.tab_main_1)
        self.hor_line_2.setGeometry(QtCore.QRect(740, 10, 391, 20))
        self.hor_line_2.setLineWidth(2)
        self.hor_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_2.setObjectName("hor_line_2")
        self.hor_line_3 = QtWidgets.QFrame(self.tab_main_1)
        self.hor_line_3.setGeometry(QtCore.QRect(740, 100, 391, 20))
        self.hor_line_3.setLineWidth(1)
        self.hor_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_3.setObjectName("hor_line_3")
        self.hor_line_4 = QtWidgets.QFrame(self.tab_main_1)
        self.hor_line_4.setGeometry(QtCore.QRect(740, 440, 391, 20))
        self.hor_line_4.setLineWidth(1)
        self.hor_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_4.setObjectName("hor_line_4")
        self.hor_line_5 = QtWidgets.QFrame(self.tab_main_1)
        self.hor_line_5.setGeometry(QtCore.QRect(740, 680, 391, 20))
        self.hor_line_5.setLineWidth(1)
        self.hor_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.hor_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hor_line_5.setObjectName("hor_line_5")
        self.ch_tmp_en_ch_1 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_1.setGeometry(QtCore.QRect(750, 500, 31, 21))
        self.ch_tmp_en_ch_1.setChecked(True)
        self.ch_tmp_en_ch_1.setObjectName("ch_tmp_en_ch_1")
        self.ch_tmp_en_ch_2 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_2.setGeometry(QtCore.QRect(800, 500, 31, 21))
        self.ch_tmp_en_ch_2.setChecked(True)
        self.ch_tmp_en_ch_2.setObjectName("ch_tmp_en_ch_2")
        self.ch_tmp_en_ch_3 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_3.setGeometry(QtCore.QRect(850, 500, 31, 21))
        self.ch_tmp_en_ch_3.setChecked(True)
        self.ch_tmp_en_ch_3.setObjectName("ch_tmp_en_ch_3")
        self.ch_tmp_en_ch_4 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_4.setGeometry(QtCore.QRect(900, 500, 31, 21))
        self.ch_tmp_en_ch_4.setChecked(True)
        self.ch_tmp_en_ch_4.setObjectName("ch_tmp_en_ch_4")
        self.ch_tmp_en_ch_5 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_5.setGeometry(QtCore.QRect(950, 500, 31, 21))
        self.ch_tmp_en_ch_5.setChecked(True)
        self.ch_tmp_en_ch_5.setObjectName("ch_tmp_en_ch_5")
        self.ch_tmp_en_ch_6 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_6.setGeometry(QtCore.QRect(1000, 500, 31, 21))
        self.ch_tmp_en_ch_6.setChecked(True)
        self.ch_tmp_en_ch_6.setObjectName("ch_tmp_en_ch_6")
        self.ch_tmp_en_ch_7 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_7.setGeometry(QtCore.QRect(1050, 500, 31, 21))
        self.ch_tmp_en_ch_7.setChecked(True)
        self.ch_tmp_en_ch_7.setObjectName("ch_tmp_en_ch_7")
        self.ch_tmp_en_ch_8 = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_tmp_en_ch_8.setGeometry(QtCore.QRect(1100, 500, 31, 21))
        self.ch_tmp_en_ch_8.setChecked(True)
        self.ch_tmp_en_ch_8.setObjectName("ch_tmp_en_ch_8")
        self.lbl_tmp_ch_disp_txt = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_tmp_ch_disp_txt.setGeometry(QtCore.QRect(740, 480, 391, 16))
        self.lbl_tmp_ch_disp_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tmp_ch_disp_txt.setObjectName("lbl_tmp_ch_disp_txt")
        self.lbl_ed_name_ch_1 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_1.setGeometry(QtCore.QRect(240, 30, 331, 20))
        self.lbl_ed_name_ch_1.setObjectName("lbl_ed_name_ch_1")
        self.lbl_ed_name_ch_2 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_2.setGeometry(QtCore.QRect(240, 120, 331, 20))
        self.lbl_ed_name_ch_2.setObjectName("lbl_ed_name_ch_2")
        self.lbl_ed_name_ch_3 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_3.setGeometry(QtCore.QRect(240, 210, 331, 20))
        self.lbl_ed_name_ch_3.setObjectName("lbl_ed_name_ch_3")
        self.lbl_ed_name_ch_4 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_4.setGeometry(QtCore.QRect(240, 300, 331, 20))
        self.lbl_ed_name_ch_4.setObjectName("lbl_ed_name_ch_4")
        self.lbl_ed_name_ch_5 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_5.setGeometry(QtCore.QRect(240, 390, 331, 20))
        self.lbl_ed_name_ch_5.setObjectName("lbl_ed_name_ch_5")
        self.lbl_ed_name_ch_6 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_6.setGeometry(QtCore.QRect(240, 480, 331, 20))
        self.lbl_ed_name_ch_6.setObjectName("lbl_ed_name_ch_6")
        self.lbl_ed_name_ch_7 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_7.setGeometry(QtCore.QRect(240, 570, 331, 20))
        self.lbl_ed_name_ch_7.setObjectName("lbl_ed_name_ch_7")
        self.lbl_ed_name_ch_8 = QtWidgets.QLineEdit(self.tab_main_1)
        self.lbl_ed_name_ch_8.setGeometry(QtCore.QRect(240, 660, 331, 20))
        self.lbl_ed_name_ch_8.setObjectName("lbl_ed_name_ch_8")
        self.btn_save_desc_ch = QtWidgets.QPushButton(self.tab_main_1)
        self.btn_save_desc_ch.setGeometry(QtCore.QRect(10, 20, 31, 23))
        self.btn_save_desc_ch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/discket-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_desc_ch.setIcon(icon1)
        self.btn_save_desc_ch.setIconSize(QtCore.QSize(20, 20))
        self.btn_save_desc_ch.setObjectName("btn_save_desc_ch")
        self.btn_load_desc_ch = QtWidgets.QPushButton(self.tab_main_1)
        self.btn_load_desc_ch.setGeometry(QtCore.QRect(42, 20, 31, 23))
        self.btn_load_desc_ch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/load-md.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_load_desc_ch.setIcon(icon2)
        self.btn_load_desc_ch.setIconSize(QtCore.QSize(20, 20))
        self.btn_load_desc_ch.setObjectName("btn_load_desc_ch")
        self.lbl_portname = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_portname.setGeometry(QtCore.QRect(740, 80, 391, 16))
        self.lbl_portname.setObjectName("lbl_portname")
        self.ch_sound = QtWidgets.QCheckBox(self.tab_main_1)
        self.ch_sound.setEnabled(False)
        self.ch_sound.setText("Sound")
        self.ch_sound.setGeometry(QtCore.QRect(1080, 350, 51, 21))
        self.ch_sound.setObjectName("ch_sound")
        self.lbl_alarm = QtWidgets.QLabel(self.tab_main_1)
        self.lbl_alarm.setGeometry(QtCore.QRect(760, 380, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_alarm.setFont(font)
        self.lbl_alarm.setStyleSheet("")
        self.lbl_alarm.setText("")
        self.lbl_alarm.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_alarm.setObjectName("lbl_alarm")
        self.tab_mainTab.addTab(self.tab_main_1, "")
        self.tab_main_2 = QtWidgets.QWidget()
        self.tab_main_2.setObjectName("tab_main_2")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_main_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 10, 711, 761))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.lay_tmp_all = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.lay_tmp_all.setContentsMargins(0, 0, 0, 0)
        self.lay_tmp_all.setObjectName("lay_tmp_all")
        self.tableI_tmp = QtWidgets.QTableWidget(self.tab_main_2)
        self.tableI_tmp.setGeometry(QtCore.QRect(730, 10, 401, 761))
        self.tableI_tmp.setColumnCount(9)
        self.tableI_tmp.setObjectName("tableI_tmp")
        self.tableI_tmp.setRowCount(0)
        self.tableI_tmp.horizontalHeader().setVisible(True)
        self.tableI_tmp.horizontalHeader().setCascadingSectionResizes(True)
        #self.tableI_tmp.horizontalHeader().setDefaultSectionSize(57)
        #self.tableI_tmp.horizontalHeader().setMinimumSectionSize(22)
        self.tableI_tmp.verticalHeader().setDefaultSectionSize(15)
        #self.tableI_tmp.verticalHeader().setHighlightSections(True)
        self.tableI_tmp.verticalHeader().setVisible(False)
        self.tab_mainTab.addTab(self.tab_main_2, "")
        self.gridLayout_2.addWidget(self.tab_mainTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_mainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.CreateTMPAxes()
        self.SetCheckTmpLabelsColors()
        self.CreateTMPTable()

    def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.lbl_time.setText(_translate("MainWindow", "00:00:00"))
            self.lbl_lturesource_txt.setText(_translate("MainWindow",
                                                        "<html><head/><body><p><span style=\" color:#ff0000;\">LTU_Resource</span></p></body></html>"))
            self.lbl_date.setText(_translate("MainWindow", "21 January 1999"))
            self.lbl_tmp_txt.setText(_translate("MainWindow", "Temperature"))
            self.lbl_tmp_ch_1.setText(_translate("MainWindow", "Channel 1"))
            self.lbl_tmp_ch_2.setText(_translate("MainWindow", "Channel 2"))
            self.lbl_tmp_ch_3.setText(_translate("MainWindow", "Channel 3"))
            self.lbl_tmp_ch_4.setText(_translate("MainWindow", "Channel 4"))
            self.lbl_tmp_ch_5.setText(_translate("MainWindow", "Channel 5"))
            self.lbl_tmp_ch_6.setText(_translate("MainWindow", "Channel 6"))
            self.lbl_tmp_ch_7.setText(_translate("MainWindow", "Channel 7"))
            self.lbl_tmp_ch_8.setText(_translate("MainWindow", "Channel 8"))
            self.lbl_act_tmp_txt.setText(_translate("MainWindow", "Actual"))
            self.lbl_act_tmp_ch_1.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_2.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_3.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_4.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_5.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_6.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_7.setText(_translate("MainWindow", "0.0"))
            self.lbl_act_tmp_ch_8.setText(_translate("MainWindow", "0.0"))
            self.lbl_set.setText(_translate("MainWindow", "Settings"))
            self.lbl_choose_txt.setText(_translate("MainWindow", "Choose COM port:"))
            self.ch_com_port.setToolTip(_translate("MainWindow", "Choose OWEN COM port"))
            self.lbl_connect_txt.setText(_translate("MainWindow", "Connect to OWEN device"))
            self.btn_connect.setToolTip(_translate("MainWindow", "Connect to COM port"))
            self.btn_connect.setText(_translate("MainWindow", "Connect"))
            self.btn_disconnect.setToolTip(_translate("MainWindow", "Disconnect COM port"))
            self.btn_disconnect.setText(_translate("MainWindow", "Disconnect"))
            self.lbl_track_txt.setText(_translate("MainWindow", "Temperature tracker"))
            self.lbl_tmp_ch_txt.setText(_translate("MainWindow", "Channel"))
            self.lbl_act_track_txt.setText(_translate("MainWindow", "Actual"))
            self.lbl_tmp_ch_1_track_txt.setText(_translate("MainWindow", "Channel 1"))
            self.lbl_tmp_ch_2_track_txt.setText(_translate("MainWindow", "Channel 2"))
            self.lbl_tmp_ch_3_track_txt.setText(_translate("MainWindow", "Channel 3"))
            self.lbl_tmp_ch_4_track_txt.setText(_translate("MainWindow", "Channel 4"))
            self.lbl_tmp_ch_5_track_txt.setText(_translate("MainWindow", "Channel 5"))
            self.lbl_tmp_ch_6_track_txt.setText(_translate("MainWindow", "Channel 6"))
            self.lbl_tmp_ch_7_track_txt.setText(_translate("MainWindow", "Channel 7"))
            self.lbl_tmp_ch_8_track_txt.setText(_translate("MainWindow", "Channel 8"))
            self.ed_tmp_min_ch_1.setText(_translate("MainWindow", "0"))
            self.lbl_min_track_txt.setText(_translate("MainWindow", "Min"))
            self.lbl_max_track_txt.setText(_translate("MainWindow", "Max"))
            self.lbl_check_track_txt.setText(_translate("MainWindow", "Check"))
            self.lbl_tmp_ch_1_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_2_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_3_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_4_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_5_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_6_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_7_track.setText(_translate("MainWindow", "0.0"))
            self.lbl_tmp_ch_8_track.setText(_translate("MainWindow", "0.0"))
            self.ed_tmp_min_ch_2.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_3.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_4.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_5.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_6.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_7.setText(_translate("MainWindow", "0"))
            self.ed_tmp_min_ch_8.setText(_translate("MainWindow", "0"))
            self.ed_tmp_max_ch_1.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_2.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_3.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_4.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_5.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_6.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_7.setText(_translate("MainWindow", "50"))
            self.ed_tmp_max_ch_8.setText(_translate("MainWindow", "50"))
            self.lbl_act_track_txt_2.setText(_translate("MainWindow", "Limit values"))
            self.lbl_save_txt.setText(_translate("MainWindow", "Save data"))
            self.ch_save_to_file.setText(_translate("MainWindow", "Save to file"))
            self.bth_create_logfile.setToolTip(_translate("MainWindow", "Create log-file to save data"))
            self.lbl_ed_logpath.setHtml(_translate("MainWindow",
                                                   "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
            self.lbl_disp_txt.setText(_translate("MainWindow", "Displaying"))
            self.gb_tmp_pts.setTitle(_translate("MainWindow", "Number of temperature points"))
            self.btn_tmp_pts_1.setText(_translate("MainWindow", "10"))
            self.btn_tmp_pts_2.setText(_translate("MainWindow", "20"))
            self.btn_tmp_pts_3.setText(_translate("MainWindow", "50"))
            self.btn_tmp_pts_4.setText(_translate("MainWindow", "100"))
            self.btn_tmp_pts_5.setText(_translate("MainWindow", "200"))
            self.btn_tmp_pts_6.setText(_translate("MainWindow", "500"))
            self.btn_tmp_pts_7.setText(_translate("MainWindow", "1000"))
            self.btn_tmp_pts_8.setText(_translate("MainWindow", "2000"))
            self.btn_tmp_pts_9.setText(_translate("MainWindow", "5000"))
            self.btn_tmp_pts_10.setText(_translate("MainWindow", "10000"))
            self.btn_tmp_pts_11.setText(_translate("MainWindow", "20000"))
            self.btn_tmp_pts_12.setText(_translate("MainWindow", "All"))
            self.lbl_totalpts_txt.setText(_translate("MainWindow", "Total points:"))
            self.lbl_tmp_totalpts.setText(_translate("MainWindow", "0"))
            self.ch_tmp_en_ch_1.setText(_translate("MainWindow", "1"))
            self.ch_tmp_en_ch_2.setText(_translate("MainWindow", "2"))
            self.ch_tmp_en_ch_3.setText(_translate("MainWindow", "3"))
            self.ch_tmp_en_ch_4.setText(_translate("MainWindow", "4"))
            self.ch_tmp_en_ch_5.setText(_translate("MainWindow", "5"))
            self.ch_tmp_en_ch_6.setText(_translate("MainWindow", "6"))
            self.ch_tmp_en_ch_7.setText(_translate("MainWindow", "7"))
            self.ch_tmp_en_ch_8.setText(_translate("MainWindow", "8"))
            self.lbl_tmp_ch_disp_txt.setText(_translate("MainWindow", "Channels displayed"))
            self.lbl_ed_name_ch_1.setToolTip(_translate("MainWindow", "Type here name of channel 1"))
            self.lbl_ed_name_ch_2.setToolTip(_translate("MainWindow", "Type here name of channel 2"))
            self.lbl_ed_name_ch_3.setToolTip(_translate("MainWindow", "Type here name of channel 3"))
            self.lbl_ed_name_ch_4.setToolTip(_translate("MainWindow", "Type here name of channel 4"))
            self.lbl_ed_name_ch_5.setToolTip(_translate("MainWindow", "Type here name of channel 5"))
            self.lbl_ed_name_ch_6.setToolTip(_translate("MainWindow", "Type here name of channel 6"))
            self.lbl_ed_name_ch_7.setToolTip(_translate("MainWindow", "Type here name of channel 7"))
            self.lbl_ed_name_ch_8.setToolTip(_translate("MainWindow", "Type here name of channel 8"))
            self.btn_save_desc_ch.setToolTip(_translate("MainWindow", "Save channels description to file"))
            self.btn_load_desc_ch.setToolTip(_translate("MainWindow", "Load channels description from file"))
            self.lbl_portname.setText(_translate("MainWindow",
                                                 "<html><head/><body><p><span style=\" color:#5500ff;\">Please, choose COM port</span></p></body></html>"))
            self.tab_mainTab.setTabText(self.tab_mainTab.indexOf(self.tab_main_1), _translate("MainWindow", "OWEN"))
            self.tab_mainTab.setTabText(self.tab_mainTab.indexOf(self.tab_main_2), _translate("MainWindow", "Reserved"))

    def CreateTMPAxes(self):
        # ---------- tmp_ch_1 ---------
        self.tmp_ch_1_Figure = Figure()
        self.tmp_ch_1_Graph = FigureCanvas(self.tmp_ch_1_Figure)
        self.lay_tmp_ch_1.addWidget(self.tmp_ch_1_Graph)
        self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.12)]
        self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_1 = Divider(self.tmp_ch_1_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_1 = Axes(self.tmp_ch_1_Figure, self.divider_tmp_ch_1.get_position())
        self.ax_tmp_ch_1.set_axes_locator(self.divider_tmp_ch_1.new_locator(nx=1, ny=1))
        self.tmp_ch_1_Figure.add_axes(self.ax_tmp_ch_1)
        self.tmp_ch1_line, = self.ax_tmp_ch_1.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_1.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_1.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_2 ---------
        self.tmp_ch_2_Figure = Figure()
        self.tmp_ch_2_Graph = FigureCanvas(self.tmp_ch_2_Figure)
        self.lay_tmp_ch_2.addWidget(self.tmp_ch_2_Graph)
        #self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        #self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_2 = Divider(self.tmp_ch_2_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_2 = Axes(self.tmp_ch_2_Figure, self.divider_tmp_ch_2.get_position())
        self.ax_tmp_ch_2.set_axes_locator(self.divider_tmp_ch_2.new_locator(nx=1, ny=1))
        self.tmp_ch_2_Figure.add_axes(self.ax_tmp_ch_2)
        self.tmp_ch2_line, = self.ax_tmp_ch_2.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_2.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_2.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_3 ---------
        self.tmp_ch_3_Figure = Figure()
        self.tmp_ch_3_Graph = FigureCanvas(self.tmp_ch_3_Figure)
        self.lay_tmp_ch_3.addWidget(self.tmp_ch_3_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        # self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_3 = Divider(self.tmp_ch_3_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_3 = Axes(self.tmp_ch_3_Figure, self.divider_tmp_ch_3.get_position())
        self.ax_tmp_ch_3.set_axes_locator(self.divider_tmp_ch_3.new_locator(nx=1, ny=1))
        self.tmp_ch_3_Figure.add_axes(self.ax_tmp_ch_3)
        self.tmp_ch3_line, = self.ax_tmp_ch_3.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_3.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_3.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_4 ---------
        self.tmp_ch_4_Figure = Figure()
        self.tmp_ch_4_Graph = FigureCanvas(self.tmp_ch_4_Figure)
        self.lay_tmp_ch_4.addWidget(self.tmp_ch_4_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        # self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_4 = Divider(self.tmp_ch_4_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_4 = Axes(self.tmp_ch_4_Figure, self.divider_tmp_ch_4.get_position())
        self.ax_tmp_ch_4.set_axes_locator(self.divider_tmp_ch_4.new_locator(nx=1, ny=1))
        self.tmp_ch_4_Figure.add_axes(self.ax_tmp_ch_4)
        self.tmp_ch4_line, = self.ax_tmp_ch_4.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_4.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_4.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_5 ---------
        self.tmp_ch_5_Figure = Figure()
        self.tmp_ch_5_Graph = FigureCanvas(self.tmp_ch_5_Figure)
        self.lay_tmp_ch_5.addWidget(self.tmp_ch_5_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        # self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_5 = Divider(self.tmp_ch_5_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_5 = Axes(self.tmp_ch_5_Figure, self.divider_tmp_ch_5.get_position())
        self.ax_tmp_ch_5.set_axes_locator(self.divider_tmp_ch_5.new_locator(nx=1, ny=1))
        self.tmp_ch_5_Figure.add_axes(self.ax_tmp_ch_5)
        self.tmp_ch5_line, = self.ax_tmp_ch_5.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_5.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_5.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_6 ---------
        self.tmp_ch_6_Figure = Figure()
        self.tmp_ch_6_Graph = FigureCanvas(self.tmp_ch_6_Figure)
        self.lay_tmp_ch_6.addWidget(self.tmp_ch_6_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        # self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_6 = Divider(self.tmp_ch_6_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_6 = Axes(self.tmp_ch_6_Figure, self.divider_tmp_ch_6.get_position())
        self.ax_tmp_ch_6.set_axes_locator(self.divider_tmp_ch_6.new_locator(nx=1, ny=1))
        self.tmp_ch_6_Figure.add_axes(self.ax_tmp_ch_6)
        self.tmp_ch6_line, = self.ax_tmp_ch_6.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_6.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_6.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_7 ---------
        self.tmp_ch_7_Figure = Figure()
        self.tmp_ch_7_Graph = FigureCanvas(self.tmp_ch_7_Figure)
        self.lay_tmp_ch_7.addWidget(self.tmp_ch_7_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        # self.v_tmp = [Size.Fixed(0.15), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_7 = Divider(self.tmp_ch_7_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp, aspect=False)
        self.ax_tmp_ch_7 = Axes(self.tmp_ch_7_Figure, self.divider_tmp_ch_7.get_position())
        self.ax_tmp_ch_7.set_axes_locator(self.divider_tmp_ch_7.new_locator(nx=1, ny=1))
        self.tmp_ch_7_Figure.add_axes(self.ax_tmp_ch_7)
        self.tmp_ch7_line, = self.ax_tmp_ch_7.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_7.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_7.get_yticklabels(), fontsize=8, visible=False)

        # ---------- tmp_ch_8 ---------
        self.tmp_ch_8_Figure = Figure()
        self.tmp_ch_8_Graph = FigureCanvas(self.tmp_ch_8_Figure)
        self.lay_tmp_ch_8.addWidget(self.tmp_ch_8_Graph)
        # self.h_tmp = [Size.Fixed(0.7), Size.Scaled(1.), Size.Fixed(.1)]
        self.v_tmp_8 = [Size.Fixed(0.35), Size.Scaled(1.), Size.Fixed(.05)]
        self.divider_tmp_ch_8 = Divider(self.tmp_ch_8_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp_8, aspect=False)
        self.ax_tmp_ch_8 = Axes(self.tmp_ch_8_Figure, self.divider_tmp_ch_8.get_position())
        self.ax_tmp_ch_8.set_axes_locator(self.divider_tmp_ch_8.new_locator(nx=1, ny=1))
        self.tmp_ch_8_Figure.add_axes(self.ax_tmp_ch_8)
        self.tmp_ch8_line, = self.ax_tmp_ch_8.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_ch_8.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_ch_8.get_yticklabels(), fontsize=8, visible=False)

        #---------- tmp_all - --------
        self.tmp_all_Figure = Figure()
        self.tmp_all_Graph = FigureCanvas(self.tmp_all_Figure)
        self.lay_tmp_all.addWidget(self.tmp_all_Graph)
        self.divider_tmp_all = Divider(self.tmp_all_Figure, (0.0, 0.0, 1., 1.), self.h_tmp, self.v_tmp_8,
                                        aspect=False)
        self.ax_tmp_all = Axes(self.tmp_all_Figure, self.divider_tmp_all.get_position())
        self.ax_tmp_all.set_axes_locator(self.divider_tmp_all.new_locator(nx=1, ny=1))
        self.tmp_all_Figure.add_axes(self.ax_tmp_all)
        self.tmp_all_line, = self.ax_tmp_all.plot([], [], color='#00FF00', linestyle='solid', label='Pulse NRG',
                                                   linewidth=1)
        plt.setp(self.ax_tmp_all.get_xticklabels(), fontsize=8, visible=False)
        plt.setp(self.ax_tmp_all.get_yticklabels(), fontsize=8, visible=False)

        self.tmp_all_GraphToolbar = NavigationToolbar(self.tmp_all_Graph, self)
        self.lay_tmp_all.addWidget(self.tmp_all_GraphToolbar)

    def SetCheckTmpLabelsColors(self):
        self.ed_tmp_min_ch_1.setStyleSheet("background: white")
        self.ed_tmp_max_ch_1.setStyleSheet("background: white")
        self.ed_tmp_min_ch_2.setStyleSheet("background: white")
        self.ed_tmp_max_ch_2.setStyleSheet("background: white")
        self.ed_tmp_min_ch_3.setStyleSheet("background: white")
        self.ed_tmp_max_ch_3.setStyleSheet("background: white")
        self.ed_tmp_min_ch_4.setStyleSheet("background: white")
        self.ed_tmp_max_ch_4.setStyleSheet("background: white")
        self.ed_tmp_min_ch_5.setStyleSheet("background: white")
        self.ed_tmp_max_ch_5.setStyleSheet("background: white")
        self.ed_tmp_min_ch_6.setStyleSheet("background: white")
        self.ed_tmp_max_ch_6.setStyleSheet("background: white")
        self.ed_tmp_min_ch_7.setStyleSheet("background: white")
        self.ed_tmp_max_ch_7.setStyleSheet("background: white")
        self.ed_tmp_min_ch_8.setStyleSheet("background: white")
        self.ed_tmp_max_ch_8.setStyleSheet("background: white")

    def CreateTMPTable(self):
        from datetime import datetime
        d1 = QtWidgets.QTableWidgetItem(datetime.now().strftime("%H:%M:%S"))

        self.tableI_tmp.setColumnCount(9)
        self.tableI_tmp.setRowCount(1)
        self.tableI_tmp.verticalHeader().setDefaultSectionSize(15)
        #self.tableI_tmp.setGeometry(750, 500, 381, 271)

        self.tableI_tmp.setHorizontalHeaderLabels(["Time", 'T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'])
        #self.tableI_tmp.setVerticalHeaderLabels(['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8'])
        self.tableI_tmp.setColumnWidth(0, 65)
        self.tableI_tmp.setColumnWidth(1, 25)
        self.tableI_tmp.setColumnWidth(2, 25)
        self.tableI_tmp.setColumnWidth(3, 25)
        self.tableI_tmp.setColumnWidth(4, 25)
        self.tableI_tmp.setColumnWidth(5, 25)
        self.tableI_tmp.setColumnWidth(6, 25)
        self.tableI_tmp.setColumnWidth(7, 25)
        self.tableI_tmp.setColumnWidth(8, 25)
        #self.tableI_tmp.setItem(0, 0, d1)